### ISSUE TITLE
Forcing battery drain for hard reset

### ISSUE THREAD

**Issue by heavyinfo** [daniel-thompson/wasp-os#67] opened 2020-08-21 17:27 UTC
Hello Daniel and wasp-os community,

I built wasp-os for P8 using commit 1a67f74319cc2176dec6fcbdd6d164370a2385ab

Like many others, I'm struck with black screen after flashing(DaFlasher) and waiting for the battery to drain completely. But I'm not sure how many days it will take.

Here are the behaviour I've noticed in order -

1. After flashing, black screen.

2. When plugged to charger, wasp-os logo is seen briefly and then disappears.
2.a When the watch is removed from the charger, bluetooth scanning shows the device as P8 but cannot be paired.
2.b P8 disappears from the scanner in some time.

3. After waiting for sometime, if the watch button is pressed for sometime, wasp-os bootloader is seen with 'start' text on the right. (Cannot be reproduced all the time)
3.a At this point the bluetooth scanner on phone shows the devices P8DFU.
3.b P8DFU disappears from the scanner in some time.

4. While repeating the above, in one instance the watch displayed a series of texts and settled in **safe mode**. (Cannot be reproduced all the time)
4.a Then the display went black as usual.
4.b  Device was lost in the scanner.

This is happening for past two days, I haven't charged the battery during this time and I keep the watch on the charger for a brief moment(<10 seconds) to get to 2.

I'm wating to see if I'm able to reach wasp-os time screen after a hard reset from battery drain, but the thing is I'm not sure when that will happen as the watch seems to go into standby mode within few seconds after 2. 3. 4.

Would it be possible to create a micropython build specifically to force hard reset? or perhaps calculating prime to drain the battery fast? Since almost everyone with P8 seems to be facing this issue.

**Comment by heavyinfo** [comment] 2020-08-24 06:27
I appreciate detailed answer @daniel-thompson 

I confirm that battery does drain overnight and the black screen persists when plugged into charger the next day - showing device as P8 in the bluetooth scanner. When the device is taken off the charger and the button is pressed it leads to wasp-os bootloader on the screen.

This is the output of Serial Bluetooth Terminal -

![Screenshot_2020-08-24-10-51-10](https://user-images.githubusercontent.com/51737091/91009256-d0282580-e5fd-11ea-9da3-fb54fb6d2c03.png)

Error loading system?

Sidenote -1: I'm unable to get wasp-os tool running yet on my environments - 
Crostini- Where I built everything successfully, probably due to missing bluez(so my fault).

Mac - 

```
./wasptool --device P8 --console
Traceback (most recent call last):
  File "./wasptool", line 279, in <module>
    console = pexpect.spawn(pynus, encoding='UTF-8')
  File "/Users/abishek/.local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/Users/abishek/.local/lib/python3.6/site-packages/pexpect/pty_spawn.py", line 277, in _spawn
    'executable: %s.' % self.command)
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: ./pynus/pynus.py.
```

RPI3- ArchLinux ARM | bluez-utils-compat

```
./wasptool --device P8 --console
Traceback (most recent call last):
  File "./wasptool", line 279, in <module>
    console = pexpect.spawn(pynus, encoding='UTF-8')
  File "/usr/lib/python3.8/site-packages/pexpect/pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/lib/python3.8/site-packages/pexpect/pty_spawn.py", line 276, in _spawn
    raise ExceptionPexpect('The command was not found or was not ' +
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: ./pynus/pynus.py.
```


_Sidenote -2: For some reason, old android phones - Android 5.1, BLE 4.1 works well with daflasher, NRF connect, Bluetooth Serial Monitor than latest android phones, chromebooks. I would recommend anyone facing detection issues, to try with an old android phone._

**Comment by daniel-thompson** [comment] 2020-08-29 12:38
Sorry for the delay... I'm just back from holiday and catching up. Can you take a look at #69 ? It looks to me like it could be the same issue. Therefore you should the same test (run `import wasp` from Safe mode) and if the results are the same for you then try the proposed workaround.

**Comment by heavyinfo** [comment] 2020-08-29 13:53
> Sorry for the delay... I'm just back from holiday and catching up

No problem, hope that the holiday was great!

>Can you take a look at #69 ? It looks to me like it could be the same issue. 

Yes! It seems that the step counter sensor is the issue and I was able to get to the wasp-os after commenting this out on your advice.
https://github.com/daniel-thompson/wasp-os/blob/01ac0d93c30a219e5cd2aa47551d1730fd34c627/wasp/wasp.py#L119

![Screenshot_2020-08-29-18-33-39](https://user-images.githubusercontent.com/51737091/91638124-cdc53180-ea2a-11ea-92a8-5ca7e0fa2d22.png)

I've included the debug message.

![Screenshot_2020-08-29-19-02-47](https://user-images.githubusercontent.com/51737091/91638129-d1f14f00-ea2a-11ea-8b19-cbb84a4fb1bb.png)

I wonder whether there is a step counter sensor in first place, a while back I had a discussion with a [Bangle.js](https://shop.espruino.com/banglejs) user and I 
was told that it doesn't have pedometer in-spite of product page mentioning otherwise. Could it be software emulated in 
the official firmware?

Only if I could get the waspostool working on a computer it could be easier to debug, does the error I get on Crostini give any details on why I'm unable to get the waspostool working there https://github.com/daniel-thompson/wasp-os/issues/67#issuecomment-678930706?

**Comment by daniel-thompson** [comment] 2020-08-29 16:20
Awesome, thanks for the udpate.

Looks like I made a mistake in the instructions, the first line should have been `watch.accel._dev.debug(True)` (the second line is correct as it was).

I've no idea if it is possible to run from Crostini or not... it depends how effective the chroot is. It would certainly try running pynus directly (instead of via wasptool) since you'd probably see the error messages more clearly. For the RPi case it looks like some of the modules from the [install guide](https://wasp-os.readthedocs.io/en/latest/install.html#building-wasp-os-from-source) are missing.

**Comment by SteveAmor** [comment] 2020-08-30 06:59
The latest versions of the P8 do not have a BMA accelerometer chip in them.  They are running the TIN5 factory firmware.  There is an ATCwatch patch for the accelerometer readings (not sure if it has made it into the official code yet) and the new chip does not have step counter hardware so it's done in software in the factory firmware.

**Comment by heavyinfo** [comment] 2020-08-30 15:08
> Looks like I made a mistake in the instructions, the first line should have been `watch.accel._dev.debug(True)` (the second line is correct as it was).

![Screenshot_2020-08-30-18-40-52](https://user-images.githubusercontent.com/51737091/91662064-983d4880-eafd-11ea-90de-a2017c170c7d.png)



> It would certainly try running pynus directly (instead of via wasptool) since you'd probably see the error messages more clearly. For the RPi case it looks like some of the modules from the [install guide](https://wasp-os.readthedocs.io/en/latest/install.html#building-wasp-os-from-source) are missing.

I did not compile submodules on RPi, sorry. But unfortunately, its bluetooth doesn't detect my watch (BLE issue? But detects iPad Air 2). Pynus scan doesn't detect any device. I will work out some other mechanism to get the debugging setup ready.

> The latest versions of the P8 do not have a BMA accelerometer chip in them.

Thanks for the confirmation @SteveAmor .  Seems **P8b**  is the new device id which uses SC7A20 for accelerometer - https://github.com/atc1441/ATCwatch/issues/18.

@daniel-thompson Should we open a separate issue to deal with missing step counter on P8b? I presume the first step would be to automatically disable the step counter when encountering **invalid sensor**.

**Comment by heavyinfo** [comment] 2020-09-18 07:01
Update: I got the wasptool running successfully on Raspberry Pi after[ fixing the bluetooth issues](https://abishekmuthian.com/fixing-bluetooth-issues-on-raspberrypi/), so should be able to contribute further regarding P8b step counter.

**Comment by seniorivn** [comment] 2020-10-25 09:03
@heavyinfo any updates? Do you use your P8b with wasp-os?

**Comment by daniel-thompson** [comment] 2020-10-25 17:24
I merged some code to fix the boot problems a little while back. That should allow a P8b to work ok for everything except the step counter (although I don"t think anyone has confirmed that).

**Comment by seniorivn** [comment] 2020-10-25 17:45
yeah, the question was about the step counter,
will confirm the state of p8b in a week or so
Shouldn't there be a separate issue for every supported device to discuss hardware issues/support status?

**Comment by daniel-thompson** [comment] 2020-11-08 17:13
> Shouldn't there be a separate issue for every supported device to discuss hardware issues/support status?

There should certainly be a seperate issue for each problem that prevents a supported feature not working as intended.

I'd rather not have issues for feature requests though (and P8b step counting is a feature request). Generally I'd prefer pull requests to be the process for new features!

Of course if there is a need to collaboratively design how to implement a feature (e.g. you are worried I won't accept or merge your work) then the issue tracker is good for specific discussion... but only when someone is ready to get to work implementing it once the design is agreed.

**Closed by daniel-thompson** 2020-11-08 17:13 UTC
