### ISSUE TITLE
MemoryError when adding Game of Life using Software app when all other apps are enabled.

### ISSUE THREAD

**Issue by Kozova1** [daniel-thompson/wasp-os#166] opened 2021-02-12 22:17 UTC
Steps to reproduce (on a PineTime):  
1. Open software app
2. Enable all apps excluding Game of Life
3. Enable Game of Life
4. Out of memory error

Reproduced on 2 PineTimes.
It also seems to happen sometimes when adding Game of Life, even without adding all apps, but I cannot reproduce this reliably.

**Comment by daniel-thompson** [comment] 2021-02-17 11:11
I have two answers for this (depending on which one you like best).

1. I can't reproduce this. Do you have any custom code in your main.py that is absorbing memory? There has been some modest memory tuning in the last month but it shouldn't be enough to make the difference on this.... for me the test app is showing >2k free with all apps enabled.

2. The purpose of the Software app is to allow us to have more apps on the watch than can fit in memory. Even if I can't reproduce today there will certainly come a point when it is not possible to enable all the apps at the same time. So I'm ok with the out-of-memory message... but what happens after that (can you dismiss it and continue using the watch or does it form a loop that you have to break with a reset?).

**Comment by Kozova1** [comment] 2021-02-17 13:13
The watch keeps working after the MemoryError.  

IMO the message could be prettified a bit, instead of a crash.

**Comment by daniel-thompson** [comment] 2021-06-20 14:27
I believe this was fixed by #199.

**Closed by daniel-thompson** 2021-06-20 14:27 UTC
