### ISSUE TITLE
Failure to upload wasp-os to pinetime using nrf connect

### ISSUE THREAD

**Issue by WilliamBehrens** [daniel-thompson/wasp-os#339] opened 2022-06-17 16:39 UTC
I was able to update my firmware on my pinetime using GadgetBridge, I went to try and upload wasp os to it following the video tutorial and after uploading the bootloader I got to the screen with the white pinecone and bluetooth logo. When I try and upload the micropython.zip file though the upload hits 100% in nrf connect but the watch doesn't do anything, it'll just sit on the bootloader screen. I can't even reflash the factory firmware with nrf connect anymore as it does the same thing.

**Comment by fgaz** [comment] 2022-06-17 16:44
Duplicate of #335, see https://github.com/daniel-thompson/wasp-os/issues/335#issuecomment-1155654561

**Closed** 2022-06-17 17:16 UTC
